pipeline { 
    agent any 
    tools { 
        maven "maven" 
        jdk "JAVA_17" 
    } 
    stages { 
        stage('Checkout') { 
            steps { 
                git branch: 'main', url: 'https://github.com/Linspi/Projet-DevOps.git' 
            } 
        } 
        stage('Build') { 
            steps { 
                sh "mvn clean package -Dmaven.test.skip=true" 
            } 
        }
        stage('SonarQube') {
            steps {
                // N'oubliez pas de remplacer VOTRE_MOT_DE_PASSE par celui de votre SonarQube
                sh "mvn sonar:sonar -Dsonar.host.url=http://192.168.33.10:9000 -Dsonar.login=admin -Dsonar.password=admin123"
            }
        }
    } 
}
